### ISSUE TITLE
[Orange Guidance Tomestone] Provided indices out of range

### ISSUE THREAD

**Issue by thoroughlyGlass** [anna-is-cute/plugin-issues#107]
Ran into this error while trying to post a message. Zone is Shaaloani, I am not maxed out on messages.

![image](https://github.com/user-attachments/assets/f2f10d07-4b58-4425-8784-bd80a7dcea53)

Thank you for Orange Guidance Tomestone, it is [my](https://cohost.org/ffxiv-messages) favorite!

**Comment by anna-is-cute** [comment]
I will take a look tomorrow c:

Also yes, I love your cohost! It was indeed me that left that anonymous message

**Comment by anna-is-cute** [comment]
Fixed!
